# General params
wandb_project: UTR_PairPred
wandb_group: Multi_spieces
result_dir: ./multi_MLP_split_hyena32k_ave_Adam_drop08
data_dir: ./data
multi_species: True
seq_data: [./data/gencode44_utr_gene_unique_max32k.csv,./data/gencode_vM33_utr_gene_unique_max32k.csv] # path to raw data csv
emb_data: [./data/gencode44_embedding_hyenadna_ave_32k.pkl,  ./data/gencode_vM33_embedding_hyenadna_ave_32k.pkl]
seed: 2023
gpus: [0,1,2,3]

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 16 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 300 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to CNN model
model:
  arch: cnn
  in_planes: 512
  out_planes: 1
  main_planes: 64
  dropout: 0.5






