# General params
wandb_project: UTR_PairPred
wandb_group: Mouse
multi_species: False
result_dir: ./results/mouse_MLP_split_large_ave_Adam_drop_complex
data_dir: ./data
conduct_test: True
seq_data: ./data/gencode_vM33_utr_gene_unique.csv # path to raw data csv
emb_data: ./data/gencode_vM33_embedding_ave.pkl
seed: 2023
gpus: [0,1,2,3]

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 16 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 150 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to CNN model
model:
  arch: mlp_split_large
  fc5utr_in: 640
  fc5utr_out: 256
  fc3utr_in: 640
  fc3utr_out: 256
  fc_common1_in: 512 # fc5utr_out + fc3utr_out
  fc_common1_out: 1024
  fc_common2_in: 1024
  fc_common2_out: 512
  fc_common3_in: 512
  fc_common3_out: 1
  dropout_5utr: 0.8
  dropout_3utr: 0.8
  dropout_fc_common1: 0.5
  dropout_fc_common2: 0.5





