# General params
wandb_project: UTR_PairPred
wandb_group: mouse
multi_species: False
result_dir: ./mouse_MLP_hyena32k
data_dir: ./data
seq_data: ./data/gencode_vM33_utr_gene_unique_max32k.csv # path to raw data csv
emb_data: ./data/gencode_vM33_embedding_hyenadna_ave_32k.pkl
seed: 2023
gpus: [0,1,2,3]

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 16 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 100 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to CNN model
model:
  arch: mlp
  fc1_in: 512
  fc1_out: 256
  fc2_in: 256
  fc2_out: 128
  fc3_in: 128
  fc3_out: 1
  dropout: 0.5




