# General params
wandb_project: UTR_PairPred
wandb_group: human
multi_species: False
result_dir: ../results/runs/attention_concat_head1
data_dir: ../data
seq_data: ../data/human/gencode44_utr_gene_unique_cdhit09.csv # path to raw data csv
emb_data: ../data/human/gencode44_embedding_forward_withpad_cdhit09.pkl
conduct_test: True
seed: 5
gpus: [0,1,2,3]
kfold: 1

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 32 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 30 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to model arch
model:
  arch: concatselfattn
  num_layers: 1
  num_heads: 1
  attn_dim: 640 # input dim
  hidden_dim: 1024 # dim of ffn intermediate
  dropout_attn: 0.5
  dropout_ffn: 0.5
  layer_norm_eps: 1e-12
  fc1_in: 640 # fc5utr_out + fc3utr_out
  fc1_out: 512
  fc2_in: 512
  fc2_out: 1
  dropout_head: 0.8









