# General params
wandb_project: UTR_PairPred
wandb_group: human_CL_10fold
wandb_mode: online
multi_species: False
result_dir: ../results/runs/contrastive_learning_10fold/
data_dir: ../data
seq_data: ../data/human/gencode44_utr_gene_unique_cdhit09.csv # path to raw data csv
emb_data: ../data/human/gencode44_embedding_ave_cdhit09.pkl
te_idx: ../data/human/TE/hek_matched_idx_cdhit09.pkl
conduct_test: True
seed: 0
gpus: [0,1,2,3]
kfold: 10

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 32 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 60 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps


# Params related to model arch
model:
  arch: contrastive
  input_dim: 640
  output_dim: 512
  dropout1: 0.8
  dropout2: 0.5








