# General params
wandb_project: UTR_PairPred
wandb_group: mlp_10fold
wandb_mode: offline
multi_species: False
result_dir: ../results/runs/MLP_split_large_ave_10fold_shuffle_seed0/
data_dir: ../data
seq_data: ../data/human/gencode44_utr_gene_unique_cdhit09.csv # path to raw data csv
emb_data: ../data/human/gencode44_embedding_ave_cdhit09.pkl
conduct_test: True
seed: 0
gpus: [0,1,2,3]
kfold: 10
# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 32 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 100 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to CNN model
model:
  arch: mlp_split_large
  fc5utr_in: 640
  fc5utr_out: 640
  fc3utr_in: 640
  fc3utr_out: 640
  fc_common1_in: 1280 # fc5utr_out + fc3utr_out
  fc_common1_out: 1024
  fc_common2_in: 1024
  fc_common2_out: 512
  fc_common3_in: 512
  fc_common3_out: 1
  dropout_5utr: 0.8
  dropout_3utr: 0.8
  dropout_fc_common1: 0.5
  dropout_fc_common2: 0.5











