# General params
wandb_project: UTR_PairPred
result_dir: ./RF_hyena
data_dir: ./data
seq_data: ./data/gencode44_utr_gene_unique_max32k.csv # path to raw data csv
emb_data: ./data/gencode44_embedding_hyenadna_ave_32k.pkl
seed: 2023
gpus: [0,1,2,3]

model:
  arch: rf

