# General params
wandb_project: UTR_PairPred
result_dir: ./CNN_ave_Adam_1e4_drop05
data_dir: ./data
seq_data: ./data/gencode44_utr_gene_unique.csv # path to raw data csv
emb_data: ./data/gencode44_embedding_ave.pkl
seed: 2023
gpus: [0,1,2,3]

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 16 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 100 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to CNN model
model:
  arch: cnn
  in_planes: 1280
  out_planes: 1
  main_planes: 128
  dropout: 0.5



