wandb_version: 1

wandb_project:
  desc: null
  value: UTR_PairPred
wandb_group:
  desc: null
  value: Multi_spieces
result_dir:
  desc: null
  value: ../multi_MLP_split_large_ave_cdhit09_model_mod
data_dir:
  desc: null
  value: ./data
multi_species:
  desc: null
  value: true
seq_data:
  desc: null
  value:
  - ../data/human/gencode44_utr_gene_unique_cdhit09.csv
  - ../data/mouse/gencode_vM33_utr_gene_unique_cdhit09.csv
emb_data:
  desc: null
  value:
  - ../data/human/gencode44_embedding_ave_cdhit09.pkl
  - ../data/mouse/gencode_vM33_embedding_ave_cdhit09.pkl
seed:
  desc: null
  value: 2023
gpus:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
train:
  desc: null
  value:
    train_bs: 32
    val_bs: 16
    lr: 1e-4
    epoch: 150
    val_epoch: 5
    grad_acc: 1
model:
  desc: null
  value:
    arch: mlp_split_large
    fc5utr_in: 640
    fc5utr_out: 640
    fc3utr_in: 640
    fc3utr_out: 640
    fc_common1_in: 1280
    fc_common1_out: 1024
    fc_common2_in: 1024
    fc_common2_out: 512
    fc_common3_in: 512
    fc_common3_out: 1
    dropout_5utr: 0.8
    dropout_3utr: 0.8
    dropout_fc_common1: 0.5
    dropout_fc_common2: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702996981.10757
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
